### ISSUE TITLE
Buggy behavior when locale is not `en`

### ISSUE THREAD

**Issue by zepumph** [phetsims/number-suite-common#22]
I tried using the query parameters `locale=es&secondLocale=en`, and in unbuilt mode, this is buggy because the "primary strings" seem to be english only, perhaps that is because there aren't translations yet.

Then I tried building the sim, and with the same query parameters, running the all_debug html, I got this assertion:

`Assertion failed:  Text should be defined and non-null. Use the empty string if needed.`

Hard to figure out the stack trace in the built version, but this seems to need to work. I'll investigate.

**Comment by marlitas** [comment]
I added a TODO for this in `NumberSuiteCommonConstants`, It seems like we're always assuming that the primary locale will be `en` in `numberToWord`. We need to add logic that eliminates that assumption.

@zepumph happy to look at this also, since I just did work in this area for https://github.com/phetsims/number-suite-common/issues/9. If that feels useful go ahead and assign me.

**Comment by marlitas** [comment]
We solved this by creating a number-common-strings folder in babel and adding all the translations there. Closing!
