### ISSUE TITLE
Some general design issues to discuss

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-suite-common#3]
@chrisklus walked me through number-play and number-compare, to explain how the sims work, etc. 

Here's a short list of design-related issues that we'd like to discuss with @amanda-phet after the holiday break.

- [x] Should we use “Ten Frames” (plural) for the accordion box title in “Twenty” screen? (effort: trivial)
_DECISION: Yes. Tracking in https://github.com/phetsims/number-play/issues/192._

- [x] In Number Compare, should the speech-synthesis button be disabled when the relational operator checkbox is unchecked? (effort: trivial)
_DECISION: Yes. Tracking in https://github.com/phetsims/number-suite-common/issues/6_

- [x] PhET games typically have button for skipping the current challenge. These games do not. Do we need a skip button? (effort: relatively easy)
_DECISION: Not needed for this sim._

- [x] UX would be more consistent if we get rid of spinners in Lab screen. Combine 4 object types into 1 toolbox. (effort: probably less than having to figure out where to place objects initially when spinner up-arrow is pressed)
_Moved to https://github.com/phetsims/number-suite-common/issues/11._

- [x] Discuss the lock feature and it's relationship to "cards" scene.
_Moved to https://github.com/phetsims/number-suite-common/issues/12_

**Comment by amanda-phet** [comment]
>  Should we use “Ten Frames” (plural) for the accordion box title in “Twenty” screen? (effort: trivial)

That sounds fine. 

>   In Number Compare, should the speech-synthesis button be disabled when the relational operator checkbox is unchecked? (effort: trivial)

Yes! 

>   PhET games typically have button for skipping the current challenge. These games do not. Do we need a skip button? (effort: relatively easy)

The Make a Ten game doesn't have this, which is the other game for this age level. It also didn't seem to be an issue at all in interviews. Since you can always get to the next challenge by just selecting every answer choice, it doesn't seem as necessary in this game as in others where you can just sit there pretty stuck. 

>   UX would be more consistent if we get rid of spinners in Lab screen. Combine 4 object types into 1 toolbox. (effort: probably less than having to figure out where to place objects initially when spinner up-arrow is pressed)

Having no spinners seems inconsistent with the Ten, Twenty, and Compare screens, which is the main reason why the Lab screen has spinners. We are using them in this sim due to the age level of users and the potential for having trouble dragging objects quickly. 

>   Discuss the lock feature and it's relationship to "cards" scene.

**Comment by pixelzoom** [comment]
The items in https://github.com/phetsims/number-suite-common/issues/3#issue-1505364718 have been addressed or moved to other issues. Closing.
