### ISSUE TITLE
CT: Assertion failed: No voices available to provided a prioritized list.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-suite-common#54]
Lots of red in CT for both number-play and number-compare, with this failure. It happens on every cycle of CT.

```
number-compare : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1678074681547/number-compare/number-compare_en.html?continuousTest=%7B%22test%22%3A%5B%22number-compare%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1678074681547%22%2C%22timestamp%22%3A1678078874831%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: No voices available to provided a prioritized list.
Error: Assertion failed: No voices available to provided a prioritized list.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1678074681547/assert/js/assert.js:28:13)
at assert (SpeechSynthesisAnnouncer.ts:497:14)
at getPrioritizedVoices (SpeechSynthesisAnnouncer.ts:543:26)
at getPrioritizedVoicesForLocale (LanguageAndVoiceControl.ts:128:81)
at listener (ReadOnlyProperty.ts:405:4)
at link (LanguageAndVoiceControl.ts:118:19)
at (SecondLanguageControl.ts:73:36)
at (NumberSuiteCommonPreferencesNode.ts:46:34)
at (NumberComparePreferencesNode.ts:20:4)
at (number-compare-main.ts:46:29)
id: Bayes Puppeteer
Snapshot from 3/5/2023, 8:51:21 PM
```

**Comment by chrisklus** [comment]
I think I figured out the problem, though I am not able to reproduce it locally. There is a link in LanguageAndVoiceControl that is calling `SpeechSynthesisAnnouncer.getPrioritizedVoicesForLocale` with no guard. And that tries to get get prioritized voices, which require the announcer to be initialized and have voices.

I believe this is not happening on non-CT machines because the preferences menu is created lazily when a user clicks it, so there are already voices populated by the time that happens. Even when I click the preferences icon immediately after the sim loads, I don't hit the assertion. So either fuzzing is that much faster at the initial click than me or puppeteer is creating the preferences menu eagerly or something like that, or maybe puppeteer never has any voices at all and this is the first code I've introduced that doesn't handle that gracefully.

**Comment by chrisklus** [comment]
Thanks to a recommendation from @zepumph on the best way to go about fixing this, I converted the link to a Multilink with the voicesProperty and am guarding the construction of the carousel with `voices.length`. We will see if this fixes the problem on CT. Leaving self-assigned.

**Comment by chrisklus** [comment]
Number Play and Compare been clear for three rounds on CT since the above commit, I think we're good to close. Thanks for the issue @pixelzoom.
